### ISSUE TITLE
 aws-iam-authenticator registery 错误. 导致无法下载对应的image

### ISSUE THREAD

**Issue by ruruiye** [nwcdlabs/kops-cn#103]
请注意，`kops-cn`是一个开源项目帮助用户更容易部署`kops`在AWS中国北京与宁夏区，`kops-cn`没有侵入式修改上游`kops`源代码，并且保持跟上游`kops`版本一致，因此大部分`kops-cn`遇到的功能性问题都会存在上游`kops`专案当中，在发布问题的时候请务必确定[查看并搜寻](https://github.com/kubernetes/kops/issues?utf8=%E2%9C%93&q=is%3Aissue+)了`kops`上游是否有人发布过同样的的问题，这里无法解决`kops`本身存在的问题或issue，如果它是一个`kops`本身的issue，请务必发布到[上游kops专案的issue](https://github.com/kubernetes/kops/issues)当中。

如果你很肯定这个issue只跟`kops-cn`有关，跟上游`kops`无关，请填写以下信息帮助我们定位问题与改进这个项目，并且尽可能提供截图给我们。

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.13.0

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
**3. What AWS region are you using(Beijing or Ningxia)?**
Ningxia
**4. What commands did you run?  What is the simplest way to reproduce this issue?**

**5. What happened after the commands executed?**

**6. What did you expect to happen?**

**7. Please provide the content of your `Makefile` and how did you run the `make` command
  You may want to remove your cluster name and other sensitive information.**

**8. Anything else do we need to know?**

aws-iam-authenticator registery 错误. 导致无法下载对应的image

```
kubecl -n kube-system get pod aws-iam-authenticator-vgshf -o yaml

  containerStatuses:
  - image: 937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/602401143452.dkr.ecr.us-west-2.amazonaws.com-amazon-aws-iam-authenticator:v0.4.0
    imageID: ""
    lastState: {}
    name: aws-iam-authenticator
    ready: false
    restartCount: 0
    state:

```
