### ISSUE TITLE
Can't pull heptio-images-authenticator

### ISSUE THREAD

**Issue by sunfuze** [nwcdlabs/kops-cn#13]
Cant pull `937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/heptio-images-authenticator:v0.3.0` when running aws-iam-authenticator.
```yaml
Containers:
  aws-iam-authenticator:
    Container ID:
    Image:         937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/heptio-images-authenticator:v0.3.0
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Args:
      server
      --config=/etc/aws-iam-authenticator/config.yaml
      --state-dir=/var/aws-iam-authenticator
      --generate-kubeconfig=/etc/kubernetes/aws-iam-authenticator/kubeconfig.yaml
```

I have seen the image in  https://github.com/nwcdlabs/kops-cn/blob/master/mirror/required-images.txt#L32.
